// Code generated by "stringer -type=NodeType node/node.go"; DO NOT EDIT

package node

import "fmt"

const _NodeType_name = "NodeNoopNodeRootNodeTextNodeNumberNodeIntNodeFloatNodeIfNodeElseNodeListNodeForeachNodeWhileNodeWrapperNodeIncludeNodeAssignmentNodeLocalVarNodeFetchFieldNodeFetchArrayElementNodeMethodCallNodeFunCallNodePrintNodePrintRawNodeFetchSymbolNodeRangeNodePlusNodeMinusNodeMulNodeDivNodeEqualsNodeNotEqualsNodeLTNodeGTNodeMakeArrayNodeGroupNodeFilterNodeMacroNodeMax"

var _NodeType_index = [...]uint16{0, 8, 16, 24, 34, 41, 50, 56, 64, 72, 83, 92, 103, 114, 128, 140, 154, 175, 189, 200, 209, 221, 236, 245, 253, 262, 269, 276, 286, 299, 305, 311, 324, 333, 343, 352, 359}

func (i NodeType) String() string {
	if i < 0 || i >= NodeType(len(_NodeType_index)-1) {
		return fmt.Sprintf("NodeType(%d)", i)
	}
	return _NodeType_name[_NodeType_index[i]:_NodeType_index[i+1]]
}
